### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"hairipi100@gmail.com",
  "password":"wfewef"
}

### register
POST http://localhost:3000/api/auth/register 

 

### verify code
POST http://localhost:3000/api/auth/verify-otp
Content-Type: application/json

{
   
}