



### POST REQUEST
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"hairipi100@gmail.com",
  "password":"wfewef"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email":"efwefwe",
  "password":"wfewef",
  "token":"eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjF9.ag9GcX2yE26FPlZiKwK0kKOX78AubkArwPTyszuODAI"
}